"""Faltaba match confimation

Revision ID: 75e9c0cef7e2
Revises: bc3f547fbc15
Create Date: 2026-01-02 13:37:11.354759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e9c0cef7e2'
down_revision = 'bc3f547fbc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_confirmations',
    sa.Column('id_confirmation', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id_match'], ),
    sa.PrimaryKeyConstraint('id_confirmation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_confirmations')
    # ### end Alembic commands ###
