"""initial tables

Revision ID: bc3f547fbc15
Revises: 
Create Date: 2026-01-02 13:24:27.529988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3f547fbc15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id_city', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_city'),
    sa.UniqueConstraint('name')
    )
    op.create_table('document_types',
    sa.Column('id_document_type', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_document_type'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genders',
    sa.Column('id_gender', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_gender'),
    sa.UniqueConstraint('name')
    )
    op.create_table('positions',
    sa.Column('id_position', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_position'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_roles',
    sa.Column('id_role', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id_team', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_team')
    )
    op.create_table('users',
    sa.Column('id_user', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('matches',
    sa.Column('id_match', sa.BigInteger(), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_match')
    )
    op.create_table('team_members',
    sa.Column('id_team_member', sa.BigInteger(), nullable=False),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('id_team', sa.BigInteger(), nullable=True),
    sa.Column('id_position', sa.BigInteger(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_position'], ['positions.id_position'], ),
    sa.ForeignKeyConstraint(['id_team'], ['teams.id_team'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_team_member'),
    sa.UniqueConstraint('id_user', 'id_team')
    )
    op.create_table('user_system_roles',
    sa.Column('id_user', sa.BigInteger(), nullable=False),
    sa.Column('id_role', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['system_roles.id_role'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_role')
    )
    op.create_table('goals',
    sa.Column('id_goal', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id_match'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id_user'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id_team'], ),
    sa.PrimaryKeyConstraint('id_goal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    op.drop_table('user_system_roles')
    op.drop_table('team_members')
    op.drop_table('matches')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('system_roles')
    op.drop_table('positions')
    op.drop_table('genders')
    op.drop_table('document_types')
    op.drop_table('cities')
    # ### end Alembic commands ###
