"""Faltaba localities

Revision ID: e5ccd04cb64f
Revises: f17975aae6b7
Create Date: 2026-01-02 13:44:30.423371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ccd04cb64f'
down_revision = 'f17975aae6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localities',
    sa.Column('id_locality', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id_city', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_city'], ['cities.id_city'], ),
    sa.PrimaryKeyConstraint('id_locality')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localities')
    # ### end Alembic commands ###
