"""Faltaba users con relaciones

Revision ID: f17975aae6b7
Revises: 75e9c0cef7e2
Create Date: 2026-01-02 13:39:19.736450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f17975aae6b7'
down_revision = '75e9c0cef7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('names', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('surnames', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('document_type_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('number_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('celphone', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('id_city', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('id_neighborhood', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('id_gender', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('zipcode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('startDate', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('lastConnection', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('id_departament', sa.Integer(), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_foreign_key(None, 'document_types', ['document_type_id'], ['id_document_type'])
        batch_op.create_foreign_key(None, 'genders', ['id_gender'], ['id_gender'])
        batch_op.create_foreign_key(None, 'cities', ['id_city'], ['id_city'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('id_departament')
        batch_op.drop_column('lastConnection')
        batch_op.drop_column('startDate')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('id_gender')
        batch_op.drop_column('id_neighborhood')
        batch_op.drop_column('id_city')
        batch_op.drop_column('birthday')
        batch_op.drop_column('address')
        batch_op.drop_column('celphone')
        batch_op.drop_column('number_id')
        batch_op.drop_column('document_type_id')
        batch_op.drop_column('surnames')
        batch_op.drop_column('names')

    # ### end Alembic commands ###
